[2025-03-12T11:33:17.066+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-12T11:33:17.096+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparkml_prediction.submit_spark_via_ssh manual__2025-03-12T11:17:10.722987+00:00 [queued]>
[2025-03-12T11:33:17.108+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparkml_prediction.submit_spark_via_ssh manual__2025-03-12T11:17:10.722987+00:00 [queued]>
[2025-03-12T11:33:17.109+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-03-12T11:33:17.122+0000] {taskinstance.py:2330} INFO - Executing <Task(SSHOperator): submit_spark_via_ssh> on 2025-03-12 11:17:10.722987+00:00
[2025-03-12T11:33:17.128+0000] {standard_task_runner.py:63} INFO - Started process 29202 to run task
[2025-03-12T11:33:17.133+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sparkml_prediction', 'submit_spark_via_ssh', 'manual__2025-03-12T11:17:10.722987+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/sparkml_prediction_dag.py', '--cfg-path', '/tmp/tmpdw4nikzw']
[2025-03-12T11:33:17.135+0000] {standard_task_runner.py:91} INFO - Job 90: Subtask submit_spark_via_ssh
[2025-03-12T11:33:17.202+0000] {task_command.py:426} INFO - Running <TaskInstance: sparkml_prediction.submit_spark_via_ssh manual__2025-03-12T11:17:10.722987+00:00 [running]> on host a0d797a25898
[2025-03-12T11:33:17.320+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sparkml_prediction' AIRFLOW_CTX_TASK_ID='submit_spark_via_ssh' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T11:17:10.722987+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T11:17:10.722987+00:00'
[2025-03-12T11:33:17.321+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-12T11:33:17.337+0000] {ssh.py:151} INFO - Creating ssh_client
[2025-03-12T11:33:17.337+0000] {ssh.py:124} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2025-03-12T11:33:17.352+0000] {base.py:84} INFO - Using connection ID 'spark_ssh_conn' for task execution.
[2025-03-12T11:33:17.353+0000] {ssh.py:301} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-03-12T11:33:17.359+0000] {transport.py:1909} INFO - Connected (version 2.0, client OpenSSH_9.6p1)
[2025-03-12T11:33:17.422+0000] {transport.py:1909} INFO - Authentication (publickey) successful!
[2025-03-12T11:33:17.423+0000] {ssh.py:480} INFO - Running command: 
    set -e  # 명령어 실패 시 즉시 종료
    echo "Starting Spark Job on 2025-03-11"

    echo "Submitting Spark Job... for 2025-03-11 data"
    /spark-3.5.3/bin/spark-submit /home/ubuntu/spark_scripts/sparkml_result.py 2025-03-11 > spark_job.log 2>&1
    exit_code=$?

    # 실행 로그 출력 (Airflow에서 확인 가능)
    if [ -f spark_job.log ]; then
        echo "=== Spark Job Log Start ==="
        cat spark_job.log
        echo "=== Spark Job Log End ==="
    else
        echo "Warning: spark_job.log not found!"
    fi

    # Spark 실패 감지
    if [ $exit_code -ne 0 ]; then
        echo "Spark Job Failed! Check logs."
        exit 1
    else
        echo "Spark Job Succeeded!"
    fi
    
[2025-03-12T11:33:17.882+0000] {ssh.py:526} INFO - Starting Spark Job on 2025-03-11
[2025-03-12T11:33:17.882+0000] {ssh.py:526} INFO - Submitting Spark Job... for 2025-03-11 data
[2025-03-12T11:33:34.659+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-12T11:33:34.674+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/ssh/operators/ssh.py", line 191, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/ssh/operators/ssh.py", line 179, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/ssh/operators/ssh.py", line 173, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 1
[2025-03-12T11:33:34.677+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=sparkml_prediction, task_id=submit_spark_via_ssh, run_id=manual__2025-03-12T11:17:10.722987+00:00, execution_date=20250312T111710, start_date=20250312T113317, end_date=20250312T113334
[2025-03-12T11:33:34.690+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 90 for task submit_spark_via_ssh (SSH operator error: exit status = 1; 29202)
[2025-03-12T11:33:34.703+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-12T11:33:34.737+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-12T11:33:34.739+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
