[2025-03-14T07:03:43.732+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-14T07:03:43.765+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_ranking_info_update.drop_ranking_info_table scheduled__2025-03-13T03:35:00+00:00 [queued]>
[2025-03-14T07:03:43.779+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_ranking_info_update.drop_ranking_info_table scheduled__2025-03-13T03:35:00+00:00 [queued]>
[2025-03-14T07:03:43.780+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-14T07:03:43.814+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): drop_ranking_info_table> on 2025-03-13 03:35:00+00:00
[2025-03-14T07:03:43.832+0000] {standard_task_runner.py:63} INFO - Started process 25940 to run task
[2025-03-14T07:03:43.839+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_ranking_info_update', 'drop_ranking_info_table', 'scheduled__2025-03-13T03:35:00+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/ranking_info_to_redshift.py', '--cfg-path', '/tmp/tmp56o201zr']
[2025-03-14T07:03:43.842+0000] {standard_task_runner.py:91} INFO - Job 172: Subtask drop_ranking_info_table
[2025-03-14T07:03:43.956+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_ranking_info_update.drop_ranking_info_table scheduled__2025-03-13T03:35:00+00:00 [running]> on host a0d797a25898
[2025-03-14T07:03:44.198+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_ranking_info_update' AIRFLOW_CTX_TASK_ID='drop_ranking_info_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T03:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-13T03:35:00+00:00'
[2025-03-14T07:03:44.199+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-14T07:03:44.238+0000] {sql.py:276} INFO - Executing: DROP TABLE IF EXISTS analytics.ranking_info;
[2025-03-14T07:03:44.266+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-14T07:03:44.317+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `redshift_default` isn't defined
[2025-03-14T07:03:44.335+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_ranking_info_update, task_id=drop_ranking_info_table, run_id=scheduled__2025-03-13T03:35:00+00:00, execution_date=20250313T033500, start_date=20250314T070343, end_date=20250314T070344
[2025-03-14T07:03:44.364+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 172 for task drop_ranking_info_table (The conn_id `redshift_default` isn't defined; 25940)
[2025-03-14T07:03:44.385+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-14T07:03:44.473+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2025-03-14T07:03:44.531+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-14T07:03:44.535+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
