[2025-03-12T11:52:31.879+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-12T11:52:31.902+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: team_color_to_parquet_dag.submit_spark_via_ssh manual__2025-03-12T11:48:01.163607+00:00 [queued]>
[2025-03-12T11:52:31.911+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: team_color_to_parquet_dag.submit_spark_via_ssh manual__2025-03-12T11:48:01.163607+00:00 [queued]>
[2025-03-12T11:52:31.912+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-03-12T11:52:31.925+0000] {taskinstance.py:2330} INFO - Executing <Task(SSHOperator): submit_spark_via_ssh> on 2025-03-12 11:48:01.163607+00:00
[2025-03-12T11:52:31.930+0000] {standard_task_runner.py:63} INFO - Started process 30411 to run task
[2025-03-12T11:52:31.933+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'team_color_to_parquet_dag', 'submit_spark_via_ssh', 'manual__2025-03-12T11:48:01.163607+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/team_color_to_parquet_dag.py', '--cfg-path', '/tmp/tmpnsvf8ptz']
[2025-03-12T11:52:31.935+0000] {standard_task_runner.py:91} INFO - Job 98: Subtask submit_spark_via_ssh
[2025-03-12T11:52:31.998+0000] {task_command.py:426} INFO - Running <TaskInstance: team_color_to_parquet_dag.submit_spark_via_ssh manual__2025-03-12T11:48:01.163607+00:00 [running]> on host a0d797a25898
[2025-03-12T11:52:32.114+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='team_color_to_parquet_dag' AIRFLOW_CTX_TASK_ID='submit_spark_via_ssh' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T11:48:01.163607+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T11:48:01.163607+00:00'
[2025-03-12T11:52:32.114+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-12T11:52:32.130+0000] {ssh.py:151} INFO - Creating ssh_client
[2025-03-12T11:52:32.131+0000] {ssh.py:124} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2025-03-12T11:52:32.146+0000] {base.py:84} INFO - Using connection ID 'spark_ssh_conn' for task execution.
[2025-03-12T11:52:32.147+0000] {ssh.py:301} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-03-12T11:52:32.152+0000] {transport.py:1909} INFO - Connected (version 2.0, client OpenSSH_9.6p1)
[2025-03-12T11:52:32.215+0000] {transport.py:1909} INFO - Authentication (publickey) successful!
[2025-03-12T11:52:32.216+0000] {ssh.py:480} INFO - Running command: 
    set -e
    echo "Starting Spark Job for Team Color Info on { data_interval_end | ds }"
    /spark-3.5.3/bin/spark-submit { params.spark_script } { data_interval_end | ds }
    exit_code=$?

    if [ $exit_code -ne 0 ]; then
        echo "Spark Job Failed! Check logs."
        exit 1
    else
        echo "Spark Job Succeeded!"
    fi
    
[2025-03-12T11:52:32.663+0000] {ssh.py:526} INFO - Starting Spark Job for Team Color Info on { data_interval_end | ds }
[2025-03-12T11:52:32.663+0000] {ssh.py:531} WARNING - bash: line 4: ds: command not found
[2025-03-12T11:52:35.380+0000] {ssh.py:531} WARNING - 25/03/12 11:52:35 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-12T11:52:35.608+0000] {ssh.py:531} WARNING - Exception in thread "main" org.apache.spark.SparkException: Failed to get main class in JAR with error 'File file:/home/ubuntu/{ does not exist'.  Please specify one with --class.
[2025-03-12T11:52:35.608+0000] {ssh.py:531} WARNING - 	at org.apache.spark.deploy.SparkSubmit.error(SparkSubmit.scala:1047)
[2025-03-12T11:52:35.608+0000] {ssh.py:531} WARNING - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:528)
[2025-03-12T11:52:35.609+0000] {ssh.py:531} WARNING - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:964)
[2025-03-12T11:52:35.609+0000] {ssh.py:531} WARNING - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
[2025-03-12T11:52:35.609+0000] {ssh.py:531} WARNING - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
[2025-03-12T11:52:35.609+0000] {ssh.py:531} WARNING - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2025-03-12T11:52:35.609+0000] {ssh.py:531} WARNING - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2025-03-12T11:52:35.609+0000] {ssh.py:531} WARNING - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2025-03-12T11:52:35.609+0000] {ssh.py:531} WARNING - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-03-12T11:52:35.703+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-12T11:52:35.718+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/ssh/operators/ssh.py", line 191, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/ssh/operators/ssh.py", line 179, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/ssh/operators/ssh.py", line 173, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 127
[2025-03-12T11:52:35.721+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=team_color_to_parquet_dag, task_id=submit_spark_via_ssh, run_id=manual__2025-03-12T11:48:01.163607+00:00, execution_date=20250312T114801, start_date=20250312T115231, end_date=20250312T115235
[2025-03-12T11:52:35.733+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 98 for task submit_spark_via_ssh (SSH operator error: exit status = 127; 30411)
[2025-03-12T11:52:35.766+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-12T11:52:35.790+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-12T11:52:35.792+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
