[2025-03-09T11:33:17.175+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-09T11:33:17.209+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_nexon_data_sequential.trigger_spark_match_info_task scheduled__2025-03-08T01:00:00+00:00 [queued]>
[2025-03-09T11:33:17.218+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_nexon_data_sequential.trigger_spark_match_info_task scheduled__2025-03-08T01:00:00+00:00 [queued]>
[2025-03-09T11:33:17.219+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-03-09T11:33:17.234+0000] {taskinstance.py:2330} INFO - Executing <Task(TriggerDagRunOperator): trigger_spark_match_info_task> on 2025-03-08 01:00:00+00:00
[2025-03-09T11:33:17.242+0000] {standard_task_runner.py:63} INFO - Started process 19238 to run task
[2025-03-09T11:33:17.247+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_nexon_data_sequential', 'trigger_spark_match_info_task', 'scheduled__2025-03-08T01:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/collect_match_info.py', '--cfg-path', '/tmp/tmpergtzoye']
[2025-03-09T11:33:17.249+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask trigger_spark_match_info_task
[2025-03-09T11:33:17.313+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_nexon_data_sequential.trigger_spark_match_info_task scheduled__2025-03-08T01:00:00+00:00 [running]> on host 40942f81e2c9
[2025-03-09T11:33:17.426+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_nexon_data_sequential' AIRFLOW_CTX_TASK_ID='trigger_spark_match_info_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-08T01:00:00+00:00'
[2025-03-09T11:33:17.427+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-09T11:33:22.010+0000] {trigger_dagrun.py:222} INFO - Waiting for submit_spark_job_v3 on 2025-03-09 11:33:17.611774+00:00 to become allowed state ['success'] ...
[2025-03-09T11:34:22.081+0000] {trigger_dagrun.py:222} INFO - Waiting for submit_spark_job_v3 on 2025-03-09 11:33:17.611774+00:00 to become allowed state ['success'] ...
[2025-03-09T11:35:22.108+0000] {trigger_dagrun.py:222} INFO - Waiting for submit_spark_job_v3 on 2025-03-09 11:33:17.611774+00:00 to become allowed state ['success'] ...
[2025-03-09T11:36:22.159+0000] {trigger_dagrun.py:222} INFO - Waiting for submit_spark_job_v3 on 2025-03-09 11:33:17.611774+00:00 to become allowed state ['success'] ...
[2025-03-09T11:37:22.231+0000] {trigger_dagrun.py:222} INFO - Waiting for submit_spark_job_v3 on 2025-03-09 11:33:17.611774+00:00 to become allowed state ['success'] ...
[2025-03-09T11:38:22.301+0000] {trigger_dagrun.py:222} INFO - Waiting for submit_spark_job_v3 on 2025-03-09 11:33:17.611774+00:00 to become allowed state ['success'] ...
[2025-03-09T11:39:22.364+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-09T11:39:22.379+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/trigger_dagrun.py", line 233, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: submit_spark_job_v3 failed with failed states failed
[2025-03-09T11:39:22.383+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=fetch_nexon_data_sequential, task_id=trigger_spark_match_info_task, run_id=scheduled__2025-03-08T01:00:00+00:00, execution_date=20250308T010000, start_date=20250309T113317, end_date=20250309T113922
[2025-03-09T11:39:22.397+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 48 for task trigger_spark_match_info_task (submit_spark_job_v3 failed with failed states failed; 19238)
[2025-03-09T11:39:22.458+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-09T11:39:22.478+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-09T11:39:22.480+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
